mod builder;
mod faces;
mod rules;

use std::{f32, marker::Sync, sync::Arc};

use serde::{Deserialize, Serialize};

use crate::{LightColor, Registry, Vec3, VoxelAccess, VoxelUpdate, AABB};

pub use builder::*;
pub use faces::*;
pub use rules::*;

pub use voxelize_core::{
    BlockRotation, CornerData, NX_ROTATION, NY_ROTATION, NZ_ROTATION, PX_ROTATION, PY_ROTATION,
    PZ_ROTATION, ROTATION_MASK, STAGE_MASK, Y_ROTATION_MASK, Y_ROT_SEGMENTS,
};

#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Block {
    /// ID of the block.
    pub id: u32,

    /// Name of the block.
    pub name: String,

    /// Whether or not the block is rotatable.
    pub rotatable: bool,

    /// Whether or not can the block rotate on the y-axis relative to it's overall rotation.
    pub y_rotatable: bool,

    pub y_rotatable_segments: YRotatableSegments,

    /// Is the block empty space?
    pub is_empty: bool,

    /// Is the block a fluid?
    pub is_fluid: bool,

    /// The force applied to entities in this fluid, pushing them in the flow direction.
    pub fluid_flow_force: f32,

    /// Multiplier applied to entity ground friction while standing on this block.
    /// 1.0 is normal grip; lower values are slipperier.
    #[serde(default = "default_ground_friction_multiplier")]
    pub ground_friction_multiplier: f32,

    /// Can this block hold the world's waterlogging fluid alongside itself?
    ///
    /// This is a capability, not a state: whether a given voxel actually holds
    /// water, and how much, lives in that voxel's own packed word. The fluid
    /// keeps its level in a field of its own, so a block is free to be both
    /// waterloggable and stateful.
    pub is_waterloggable: bool,

    /// Is this the fluid that waterlogging fills voxels with? Exactly one
    /// block in a registry may claim this.
    pub is_waterlogging_fluid: bool,

    /// Does the block emit light?
    pub is_light: bool,

    /// Can this block be passed through?
    pub is_passable: bool,

    /// Can entities climb this block?
    pub is_climbable: bool,

    /// Is the block opaque?
    pub is_opaque: bool,

    /// Red-light level of the block.
    pub red_light_level: u32,

    /// Green-light level of the block.
    pub green_light_level: u32,

    /// Blue-light level of the block.
    pub blue_light_level: u32,

    /// Do faces of this transparent block need to be rendered?
    pub transparent_standalone: bool,

    /// The faces that this block has to render.
    pub faces: Vec<BlockFace>,

    /// Bounding boxes of this block.
    pub aabbs: Vec<AABB>,

    /// Is the block overall see-through? Opacity equals 0.1 or something?
    pub is_see_through: bool,

    /// Does this block prevent fluids from rendering faces against it?
    pub occludes_fluid: bool,

    pub is_plant: bool,

    /// Declares whether this block auto-clears when its support is removed.
    /// Wired through [`BlockBuilder::requires_support`] into `active_fn`.
    #[serde(default)]
    pub requires_support: SupportRequirement,

    /// Is this block transparent from looking from all 6 sides?
    /// The order is: px, py, pz, nx, ny, nz.
    pub is_transparent: [bool; 6],

    /// Optical density for Beer-Lambert light transmission through this block.
    /// `0` keeps normal air rules. `1` is leaves-scale. `2` is water-scale.
    /// Transmission per unit is ≈ e^(-0.143) (222/256).
    #[serde(default)]
    pub light_attenuation: u8,

    pub is_entity: bool,

    pub default_entity_json: Option<String>,

    /// Whether or not this block has dynamic aabb and face generation. This is
    /// automatically generated by the engine, and if `true`, client-side code
    /// should also have a corresponding dynamic function.
    pub is_dynamic: bool,

    pub dynamic_patterns: Option<Vec<BlockDynamicPattern>>,

    /// Dynamic aabb and face generation function. Defaults to `None`.
    #[serde(skip)]
    pub dynamic_fn: Option<
        Arc<
            dyn Fn(Vec3<i32>, &dyn VoxelAccess, &Registry) -> (Vec<BlockFace>, Vec<AABB>, [bool; 6])
                + Send
                + Sync,
        >,
    >,

    #[serde(skip)]
    pub active_updater: Option<
        Arc<dyn Fn(Vec3<i32>, &dyn VoxelAccess, &Registry) -> Vec<VoxelUpdate> + Send + Sync>,
    >,

    #[serde(skip)]
    pub active_ticker:
        Option<Arc<dyn Fn(Vec3<i32>, &dyn VoxelAccess, &Registry) -> u64 + Send + Sync>>,

    pub is_active: bool,

    /// When true, the subchunk random-tick sampler may invoke this block's
    /// `active_updater` (scheduled via `mark_voxel_active` at the current
    /// tick). Default false -- copper/fluids stay neighbor/scheduled only;
    /// plant growth opts in explicitly.
    #[serde(default)]
    pub is_random_tickable: bool,
}

impl Block {
    pub fn new(name: &str) -> BlockBuilder {
        BlockBuilder::new(name)
    }

    pub fn has_torch_light(&self) -> bool {
        self.red_light_level > 0 || self.green_light_level > 0 || self.blue_light_level > 0
    }

    /// Check if block emits light at a specific position (considering dynamic patterns)
    pub fn is_light_at(&self, pos: &Vec3<i32>, space: &dyn VoxelAccess) -> bool {
        // Check dynamic patterns first
        if let Some(dynamic_patterns) = &self.dynamic_patterns {
            for pattern in dynamic_patterns {
                for part in &pattern.parts {
                    if Self::evaluate_rule(&part.rule, pos, space) {
                        // If this part matches and has any light levels defined, it's a light
                        if part.red_light_level.is_some()
                            || part.green_light_level.is_some()
                            || part.blue_light_level.is_some()
                        {
                            return part.red_light_level.unwrap_or(0) > 0
                                || part.green_light_level.unwrap_or(0) > 0
                                || part.blue_light_level.unwrap_or(0) > 0;
                        }
                    }
                }
            }
        }

        // Fall back to static check
        self.is_light
    }

    pub fn get_aabbs(
        &self,
        pos: &Vec3<i32>,
        space: &dyn VoxelAccess,
        registry: &Registry,
    ) -> Vec<AABB> {
        if self.is_dynamic {
            if let Some(dynamic_patterns) = &self.dynamic_patterns {
                for pattern in dynamic_patterns {
                    let (_, aabbs, __) = Block::match_dynamic_pattern(pattern, pos, space);
                    if aabbs.len() > 0 {
                        return aabbs.to_owned();
                    }
                }
                return self.aabbs.clone();
            }

            (self.dynamic_fn.as_ref().unwrap())(pos.to_owned(), space, registry).1
        } else {
            self.aabbs.clone()
        }
    }

    pub fn get_faces(
        &self,
        pos: &Vec3<i32>,
        space: &dyn VoxelAccess,
        registry: &Registry,
    ) -> Vec<BlockFace> {
        if self.is_dynamic {
            if let Some(dynamic_patterns) = &self.dynamic_patterns {
                for pattern in dynamic_patterns {
                    let (faces, _, __) = Block::match_dynamic_pattern(pattern, pos, space);
                    if faces.len() > 0 {
                        return faces.to_owned();
                    }
                }
                return self.faces.clone();
            }

            (self.dynamic_fn.as_ref().unwrap())(pos.to_owned(), space, registry).0
        } else {
            self.faces.clone()
        }
    }

    pub fn get_torch_light_level(&self, color: &LightColor) -> u32 {
        match *color {
            LightColor::Red => self.red_light_level,
            LightColor::Green => self.green_light_level,
            LightColor::Blue => self.blue_light_level,
            LightColor::Sunlight => 0,
        }
    }

    /// Get torch light level considering dynamic patterns (if any)
    pub fn get_torch_light_level_at(
        &self,
        pos: &Vec3<i32>,
        space: &dyn VoxelAccess,
        color: &LightColor,
    ) -> u32 {
        // Check if we have dynamic patterns with light levels
        if let Some(dynamic_patterns) = &self.dynamic_patterns {
            for pattern in dynamic_patterns {
                for part in &pattern.parts {
                    if Self::evaluate_rule(&part.rule, pos, space) {
                        // If this part matches and has light levels defined, use them
                        match *color {
                            LightColor::Red => {
                                if let Some(level) = part.red_light_level {
                                    return level;
                                }
                            }
                            LightColor::Green => {
                                if let Some(level) = part.green_light_level {
                                    return level;
                                }
                            }
                            LightColor::Blue => {
                                if let Some(level) = part.blue_light_level {
                                    return level;
                                }
                            }
                            LightColor::Sunlight => return 0,
                        }
                    }
                }
            }
        }

        // Fall back to static light levels
        self.get_torch_light_level(color)
    }

    pub fn get_rotated_transparency(&self, rotation: &BlockRotation) -> [bool; 6] {
        rotation.rotate_transparency(self.is_transparent)
    }

    /// Evaluate the dynamic pattern and return the combined faces and AABBs based on the rules.
    fn evaluate_dynamic_pattern(
        pattern: &BlockDynamicPattern,
        pos: &Vec3<i32>,
        space: &dyn VoxelAccess,
    ) -> (Vec<BlockFace>, Vec<AABB>, [bool; 6]) {
        let mut combined_faces = Vec::new();
        let mut combined_aabbs = Vec::new();
        let mut combined_transparency = [false; 6];

        for part in &pattern.parts {
            if Self::evaluate_rule(&part.rule, pos, space) {
                combined_faces.extend(part.faces.clone());
                combined_aabbs.extend(part.aabbs.clone());
                for (i, &is_transparent) in part.is_transparent.iter().enumerate() {
                    combined_transparency[i] = combined_transparency[i] || is_transparent;
                }
            }
        }

        (combined_faces, combined_aabbs, combined_transparency)
    }

    fn evaluate_rule(rule: &BlockRule, pos: &Vec3<i32>, space: &dyn VoxelAccess) -> bool {
        match rule {
            BlockRule::None => true,
            BlockRule::Simple(simple_rule) => {
                let vx = simple_rule.offset.0 + pos.0;
                let vy = simple_rule.offset.1 + pos.1;
                let vz = simple_rule.offset.2 + pos.2;

                let id_match = simple_rule.id.map_or(true, |rule_id| {
                    let id = space.get_voxel(vx, vy, vz);
                    id == rule_id
                });

                let rotation_match = simple_rule.rotation.as_ref().map_or(true, |rule_rotation| {
                    let rotation = space.get_voxel_rotation(vx, vy, vz);
                    rotation == *rule_rotation
                });

                let stage_match = simple_rule.stage.map_or(true, |rule_stage| {
                    let stage = space.get_voxel_stage(vx, vy, vz);
                    stage == rule_stage
                });

                id_match && rotation_match && stage_match
            }
            BlockRule::Combination { logic, rules } => {
                match logic {
                    BlockRuleLogic::And => rules
                        .iter()
                        .all(|rule| Self::evaluate_rule(rule, pos, space)),
                    BlockRuleLogic::Or => rules
                        .iter()
                        .any(|rule| Self::evaluate_rule(rule, pos, space)),
                    BlockRuleLogic::Not => !rules
                        .iter()
                        .any(|rule| Self::evaluate_rule(rule, pos, space)),
                    // Extend with other logic types as needed
                }
            }
        }
    }

    fn match_dynamic_pattern(
        pattern: &BlockDynamicPattern,
        pos: &Vec3<i32>,
        space: &dyn VoxelAccess,
    ) -> (Vec<BlockFace>, Vec<AABB>, [bool; 6]) {
        Self::evaluate_dynamic_pattern(&pattern, pos, space)
    }

    pub fn to_mesher_block(&self) -> voxelize_mesher::Block {
        voxelize_mesher::Block {
            id: self.id,
            name: self.name.clone(),
            name_lower: self.name.to_lowercase(),
            rotatable: self.rotatable,
            y_rotatable: self.y_rotatable,
            is_empty: self.is_empty,
            is_fluid: self.is_fluid,
            is_waterloggable: self.is_waterloggable,
            is_waterlogging_fluid: self.is_waterlogging_fluid,
            is_opaque: self.is_opaque,
            is_see_through: self.is_see_through,
            is_transparent: self.is_transparent,
            transparent_standalone: self.transparent_standalone,
            occludes_fluid: self.occludes_fluid,
            is_plant: self.is_plant,
            faces: self.faces.iter().map(|f| f.to_mesher_face()).collect(),
            aabbs: self.aabbs.clone(),
            dynamic_patterns: self
                .dynamic_patterns
                .as_ref()
                .map(|patterns| patterns.iter().map(|p| p.to_mesher_pattern()).collect()),
        }
    }
}

#[derive(Clone, Serialize, Deserialize)]
pub enum YRotatableSegments {
    All,
    Eight,
    Four,
}

impl Default for YRotatableSegments {
    fn default() -> Self {
        Self::All
    }
}

fn default_ground_friction_multiplier() -> f32 {
    1.0
}
