packages:
  - docs
  - packages/*
  - crates/wasm-mesher
  - crates/wasm-lighter
  - examples/client

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@voxelize/core'
  - bufferutil
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - nx
  - protobufjs
  - utf-8-validate
