#!/usr/bin/env node
//
// Engine-boundary gate: Voxelize is the engine, and it must not know what any
// game built on it contains. This fails when engine source names a consumer's
// blocks, items, creatures, worlds or game terms, or reaches into a
// consumer's tree through an import or a path.
//
// The consumer vocabulary arrives as digests (denylist.json), generated by the
// consumer from its own registries, so this repository never carries the
// names it forbids. A consumer's CI can pass its current vocabulary in plain
// text with --vocabulary, replacing that consumer's hashed groups, so a name
// added downstream is caught before the digests here are regenerated.
//
// A legitimate hit is excused in excuses.json, with a reason per entry. An
// excuse that no longer matches anything fails the gate too, so the list can
// only describe what is actually there.
//
// Usage:
//   node scripts/engine-boundary/check.mjs
//   node scripts/engine-boundary/check.mjs --vocabulary <plain.json> [--json]
//
// Exit codes: 0 clean, 1 violations or stale excuses, 2 the gate could not run.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));

export const ENGINE_ROOT = path.resolve(scriptDir, "..", "..");
export const DENYLIST_PATH = path.join(scriptDir, "denylist.json");
export const EXCUSES_PATH = path.join(scriptDir, "excuses.json");
export const HASH_SCHEME = "fnv1a32+mix32/v1";

const SELF_FILES = new Set(
  ["check.mjs", "check.test.mjs", "denylist.json", "excuses.json"].map(
    (name) => `scripts/engine-boundary/${name}`,
  ),
);

// Lockfiles carry third-party package names, which are neither engine code
// nor anything this repository chose to write.
const SKIPPED_BASENAMES = new Set([
  "pnpm-lock.yaml",
  "Cargo.lock",
  "package-lock.json",
  "yarn.lock",
]);

const IMPORT_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".mts",
  ".cts",
]);

export class GateError extends Error {}

// ---------------------------------------------------------------------------
// Tokens and digests. The consumer's generator imports these, so both sides
// agree on what a term is: identifiers are split on case and punctuation, so
// "DuneSpitter", "dune_spitter", "dune-spitter" and "Dune Spitter" are all
// the phrase "dune spitter".

const RUN_PATTERN = /[A-Za-z0-9]+/g;
const PART_PATTERN =
  /[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+[0-9]*|[A-Z]+[0-9]*|[0-9]+/g;

export function tokenize(text) {
  const tokens = [];
  RUN_PATTERN.lastIndex = 0;
  let run;
  while ((run = RUN_PATTERN.exec(text)) !== null) {
    PART_PATTERN.lastIndex = 0;
    let part;
    while ((part = PART_PATTERN.exec(run[0])) !== null) {
      const start = run.index + part.index;
      tokens.push({
        word: part[0].toLowerCase(),
        start,
        end: start + part[0].length,
      });
    }
  }
  return tokens;
}

export function normalizePhrase(text) {
  return tokenize(text)
    .map((token) => token.word)
    .join(" ");
}

const FNV_OFFSET = 0x811c9dc5;
const FNV_PRIME = 0x01000193;
const MIX_SEED = 0x2545f491;
const MIX_PRIME = 0x9e3779b1;
const SPACE = 32;

function fnvStep(hash, code) {
  return Math.imul(hash ^ code, FNV_PRIME);
}

function mixStep(hash, code) {
  const mixed = Math.imul(hash ^ code, MIX_PRIME);
  return (mixed << 13) | (mixed >>> 19);
}

function finalizeMix(hash) {
  let value = hash;
  value ^= value >>> 16;
  value = Math.imul(value, 0x85ebca6b);
  value ^= value >>> 13;
  value = Math.imul(value, 0xc2b2ae35);
  value ^= value >>> 16;
  return value >>> 0;
}

// 53 bits of the 64-bit digest: exact in a double, so lookups stay a Set of
// numbers instead of a string per n-gram.
function lookupKey(fnv, mix) {
  return (fnv >>> 0) * 0x200000 + (finalizeMix(mix) >>> 11);
}

export function digestPhrase(phrase) {
  let fnv = FNV_OFFSET;
  let mix = MIX_SEED;
  for (let index = 0; index < phrase.length; index += 1) {
    const code = phrase.charCodeAt(index);
    fnv = fnvStep(fnv, code);
    mix = mixStep(mix, code);
  }
  return (
    (fnv >>> 0).toString(16).padStart(8, "0") +
    finalizeMix(mix).toString(16).padStart(8, "0")
  );
}

export function keyFromDigest(digest) {
  if (!/^[0-9a-f]{16}$/.test(digest)) {
    throw new GateError(`malformed digest "${digest}" (want 16 hex chars)`);
  }
  const fnv = Number.parseInt(digest.slice(0, 8), 16);
  const mix = Number.parseInt(digest.slice(8), 16);
  return fnv * 0x200000 + (mix >>> 11);
}

// ---------------------------------------------------------------------------
// Denylist

function readJson(file, label) {
  let text;
  try {
    text = readFileSync(file, "utf8");
  } catch (error) {
    throw new GateError(`cannot read ${label} at ${file}: ${error.message}`);
  }
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new GateError(
      `${label} at ${file} is not valid JSON: ${error.message}`,
    );
  }
}

function validateGroup(group, origin) {
  for (const field of ["id", "consumer", "kind", "why"]) {
    if (typeof group[field] !== "string" || group[field].length === 0) {
      throw new GateError(`${origin}: a group is missing "${field}"`);
    }
  }
  const hasDigests = Array.isArray(group.digests);
  const hasTerms = Array.isArray(group.terms);
  if (hasDigests === hasTerms) {
    throw new GateError(
      `${origin}: group ${group.id} needs exactly one of "digests" or "terms"`,
    );
  }
}

// Merges plain-text groups over hashed ones: a consumer that supplies its
// current vocabulary replaces every hashed group it owns.
export function buildDenylist(hashed, vocabulary) {
  if (hashed.hash !== HASH_SCHEME) {
    throw new GateError(
      `denylist hash scheme "${hashed.hash}" is not "${HASH_SCHEME}"; regenerate it`,
    );
  }
  const replaced = new Set((vocabulary?.groups ?? []).map((g) => g.consumer));
  const groups = [
    ...(hashed.groups ?? []).filter((group) => !replaced.has(group.consumer)),
    ...(vocabulary?.groups ?? []),
  ];

  const byKey = new Map();
  let maxWords = 1;
  groups.forEach((group, index) => {
    validateGroup(group, group.terms ? "vocabulary" : "denylist.json");
    if (group.terms) {
      for (const term of group.terms) {
        const phrase = normalizePhrase(term);
        if (!phrase) continue;
        maxWords = Math.max(maxWords, phrase.split(" ").length);
        const key = keyFromDigest(digestPhrase(phrase));
        if (!byKey.has(key)) byKey.set(key, index);
      }
    } else {
      for (const digest of group.digests) {
        const key = keyFromDigest(digest);
        if (!byKey.has(key)) byKey.set(key, index);
      }
    }
  });
  maxWords = Math.max(maxWords, hashed.maxWords ?? 1);

  const consumers = {
    ...(hashed.consumers ?? {}),
    ...(vocabulary?.consumers ?? {}),
  };
  return { groups, byKey, maxWords, consumers };
}

// ---------------------------------------------------------------------------
// Scanning

function findTermHits(text, denylist, onHit) {
  const tokens = tokenize(text);
  const { byKey, maxWords } = denylist;
  for (let first = 0; first < tokens.length; first += 1) {
    let fnv = FNV_OFFSET;
    let mix = MIX_SEED;
    const last = Math.min(tokens.length, first + maxWords);
    for (let index = first; index < last; index += 1) {
      if (index > first) {
        fnv = fnvStep(fnv, SPACE);
        mix = mixStep(mix, SPACE);
      }
      const word = tokens[index].word;
      for (let char = 0; char < word.length; char += 1) {
        const code = word.charCodeAt(char);
        fnv = fnvStep(fnv, code);
        mix = mixStep(mix, code);
      }
      const groupIndex = byKey.get(lookupKey(fnv, mix));
      if (groupIndex !== undefined) {
        onHit({
          groupIndex,
          start: tokens[first].start,
          end: tokens[index].end,
          phrase: tokens
            .slice(first, index + 1)
            .map((token) => token.word)
            .join(" "),
        });
      }
    }
  }
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isInsideRoot(root, target) {
  const relative = path.relative(root, target);
  return (
    relative === "" ||
    (!relative.startsWith("..") && !path.isAbsolute(relative))
  );
}

const RELATIVE_PATH_PATTERN = /(?<![\w@.\-/\\])((?:\.\.\/)+[\w@.\-/]*)/g;
const IMPORT_PATTERNS = [
  /\bfrom\s*["'`]([^"'`\n]+)["'`]/g,
  /\bimport\s*\(\s*["'`]([^"'`\n]+)["'`]/g,
  /\bimport\s+["'`]([^"'`\n]+)["'`]/g,
  /\brequire\s*\(\s*["'`]([^"'`\n]+)["'`]/g,
];

function buildConsumerMatchers(consumers) {
  const matchers = [];
  for (const [name, spec] of Object.entries(consumers)) {
    const paths = spec.paths ?? [];
    if (paths.length > 0) {
      matchers.push({
        consumer: name,
        rule: "consumer-path",
        pattern: new RegExp(
          `(?<![\\w.\\-/])(${paths.map(escapeRegExp).join("|")})[\\w.\\-/]*`,
          "g",
        ),
      });
    }
    const specifiers = [
      ...(spec.aliases ?? []).map((alias) => ({ alias })),
      ...(spec.packages ?? []).map((pkg) => ({ pkg })),
    ];
    if (specifiers.length > 0) {
      matchers.push({ consumer: name, rule: "consumer-import", specifiers });
    }
  }
  return matchers;
}

function matchesSpecifier(specifier, { alias, pkg }) {
  if (alias) return specifier.startsWith(alias);
  return specifier === pkg || specifier.startsWith(`${pkg}/`);
}

// Engine logic that branches on a literal block name knows what blocks exist,
// however generic the name. Tests, examples and docs register names freely;
// shipped engine code asks the registry about properties instead.
const ENGINE_SOURCE =
  /^(server|crates\/[^/]+\/src|packages\/[^/]+\/src)\/.+\.(rs|ts|tsx)$/;
const TEST_SOURCE =
  /(\.test\.tsx?$|(^|\/)tests?\/|(^|\/|_)tests?\.rs$|(^|\/)benches\/)/;
const RUST_TEST_MODULE = /^\s*#\[cfg\(test\)\]/;
const BLOCK_NAME_LITERALS = [
  /\.name\s*(?:==|!=)\s*"([A-Z][^"]*)"/g,
  /\b(?:get_block_by_name|get_id_by_name|getBlockByName|getBlockIdByName)\(\s*["'`]([^"'`]+)["'`]/g,
  /\bblock\.name\s*(?:===|!==)\s*["'`]([^"'`]+)["'`]/g,
];

function isEngineSource(relPath) {
  return ENGINE_SOURCE.test(relPath) && !TEST_SOURCE.test(relPath);
}

export function scanText({ relPath, text, denylist, root = ENGINE_ROOT }) {
  const violations = [];
  const consumerMatchers = buildConsumerMatchers(denylist.consumers);
  const extension = path.extname(relPath);
  const fileDir = path.dirname(path.join(root, relPath));
  const lines = text.split("\n");
  let isCheckingBlockNames = isEngineSource(relPath);

  lines.forEach((line, lineIndex) => {
    if (
      isCheckingBlockNames &&
      extension === ".rs" &&
      RUST_TEST_MODULE.test(line)
    ) {
      isCheckingBlockNames = false;
    }
    if (isCheckingBlockNames) {
      for (const pattern of BLOCK_NAME_LITERALS) {
        pattern.lastIndex = 0;
        let found;
        while ((found = pattern.exec(line)) !== null) {
          violations.push({
            rule: "block-name-literal",
            path: relPath,
            line: lineIndex + 1,
            column: found.index + 1,
            text: found[0],
            why:
              `engine logic keyed on the block named "${found[1]}"; the engine must not ` +
              "know what blocks exist, so express this as a block property or a hook " +
              "the consumer registers",
          });
        }
      }
    }

    findTermHits(line, denylist, (hit) => {
      const group = denylist.groups[hit.groupIndex];
      violations.push({
        rule: "term",
        path: relPath,
        line: lineIndex + 1,
        column: hit.start + 1,
        text: line.slice(hit.start, hit.end),
        term: hit.phrase,
        consumer: group.consumer,
        kind: group.kind,
        why: group.why,
        source: group.source,
      });
    });

    RELATIVE_PATH_PATTERN.lastIndex = 0;
    let relative;
    while ((relative = RELATIVE_PATH_PATTERN.exec(line)) !== null) {
      const target = path.resolve(fileDir, relative[1]);
      if (!isInsideRoot(root, target)) {
        violations.push({
          rule: "path-escape",
          path: relPath,
          line: lineIndex + 1,
          column: relative.index + 1,
          text: relative[1],
          why:
            "this relative path resolves outside the engine root, into whatever tree " +
            "embeds it; the engine must build and read without a consumer next to it",
        });
      }
    }

    for (const matcher of consumerMatchers) {
      if (matcher.rule === "consumer-path") {
        matcher.pattern.lastIndex = 0;
        let found;
        while ((found = matcher.pattern.exec(line)) !== null) {
          violations.push({
            rule: "consumer-path",
            path: relPath,
            line: lineIndex + 1,
            column: found.index + 1,
            text: found[0],
            consumer: matcher.consumer,
            why:
              `a path into the ${matcher.consumer} tree; the engine documents and ` +
              "tests itself, and points at consumers only through public extension points",
          });
        }
      } else if (IMPORT_EXTENSIONS.has(extension)) {
        for (const pattern of IMPORT_PATTERNS) {
          pattern.lastIndex = 0;
          let found;
          while ((found = pattern.exec(line)) !== null) {
            const specifier = found[1];
            if (
              matcher.specifiers.some((spec) =>
                matchesSpecifier(specifier, spec),
              )
            ) {
              violations.push({
                rule: "consumer-import",
                path: relPath,
                line: lineIndex + 1,
                column: found.index + 1,
                text: specifier,
                consumer: matcher.consumer,
                why:
                  `imports ${matcher.consumer} code (an alias or package of that consumer); ` +
                  "the dependency must point the other way",
              });
            }
          }
        }
      }
    }
  });

  return violations;
}

export function scanPath({ relPath, denylist }) {
  const violations = [];
  findTermHits(relPath, denylist, (hit) => {
    const group = denylist.groups[hit.groupIndex];
    violations.push({
      rule: "term",
      path: relPath,
      line: 0,
      column: hit.start + 1,
      text: relPath.slice(hit.start, hit.end),
      term: hit.phrase,
      consumer: group.consumer,
      kind: group.kind,
      why: group.why,
      source: group.source,
    });
  });
  return violations;
}

export function listEngineFiles(root = ENGINE_ROOT) {
  const result = spawnSync(
    "git",
    ["ls-files", "-z", "--cached", "--others", "--exclude-standard"],
    { cwd: root, encoding: "utf8", maxBuffer: 1 << 28 },
  );
  if (result.error) {
    throw new GateError(`cannot run git in ${root}: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new GateError(
      `git ls-files failed in ${root}: ${result.stderr.trim() || `status ${result.status}`}`,
    );
  }
  return result.stdout
    .split("\0")
    .filter(Boolean)
    .filter((relPath) => !SELF_FILES.has(relPath))
    .filter((relPath) => !SKIPPED_BASENAMES.has(path.basename(relPath)));
}

export function scanEngine({ root = ENGINE_ROOT, denylist, files }) {
  const violations = [];
  for (const relPath of files ?? listEngineFiles(root)) {
    const absolute = path.join(root, relPath);
    let stats;
    try {
      stats = statSync(absolute);
    } catch {
      continue;
    }
    if (!stats.isFile()) continue;

    violations.push(...scanPath({ relPath, denylist }));

    const buffer = readFileSync(absolute);
    if (buffer.includes(0)) continue;
    violations.push(
      ...scanText({ relPath, text: buffer.toString("utf8"), denylist, root }),
    );
  }
  return violations;
}

// ---------------------------------------------------------------------------
// Excuses

export function applyExcuses({ violations, excuses, root = ENGINE_ROOT }) {
  const entries = excuses.excuses ?? [];
  entries.forEach((excuse, index) => {
    if (typeof excuse.path !== "string" || excuse.path.length === 0) {
      throw new GateError(`excuses.json entry ${index} has no "path"`);
    }
    if (typeof excuse.reason !== "string" || excuse.reason.trim().length < 12) {
      throw new GateError(
        `excuses.json entry for ${excuse.path} needs a "reason" that says why the hit is legitimate`,
      );
    }
  });

  const covers = (excuse, violation) => {
    const isPathMatch = excuse.path.endsWith("/")
      ? violation.path.startsWith(excuse.path)
      : violation.path === excuse.path;
    if (!isPathMatch) return false;
    const rule = excuse.rule ?? "term";
    if (rule !== violation.rule) return false;
    if (rule !== "term" || !excuse.terms) return true;
    return excuse.terms.some(
      (term) => normalizePhrase(term) === violation.term,
    );
  };

  const used = entries.map((excuse) => ({
    excuse,
    isUsed: false,
    usedTerms: new Set(),
  }));

  const remaining = violations.filter((violation) => {
    let isExcused = false;
    for (const record of used) {
      if (covers(record.excuse, violation)) {
        record.isUsed = true;
        if (violation.term) record.usedTerms.add(violation.term);
        isExcused = true;
      }
    }
    return !isExcused;
  });

  const stale = [];
  for (const { excuse, isUsed, usedTerms } of used) {
    const isPresent = existsSync(path.join(root, excuse.path));
    if (!isPresent) {
      stale.push({ excuse, detail: `${excuse.path} no longer exists` });
      continue;
    }
    if (!isUsed) {
      stale.push({
        excuse,
        detail: `nothing under ${excuse.path} trips the ${excuse.rule ?? "term"} rule any more`,
      });
      continue;
    }
    for (const term of excuse.terms ?? []) {
      if (!usedTerms.has(normalizePhrase(term))) {
        stale.push({
          excuse,
          detail: `"${term}" no longer appears in ${excuse.path}`,
        });
      }
    }
  }

  return { remaining, stale };
}

// ---------------------------------------------------------------------------
// Reporting

function describe(violation) {
  if (violation.rule === "term") {
    const source = violation.source ? ` [${violation.source}]` : "";
    return `${violation.kind} of ${violation.consumer}${source}: ${violation.why}`;
  }
  return violation.why;
}

export function formatReport({
  remaining,
  stale,
  pending = [],
  fileCount,
  elapsedMs,
}) {
  const lines = [];
  if (remaining.length > 0) {
    lines.push(`engine boundary: ${remaining.length} violation(s)`, "");
    for (const violation of remaining) {
      const where =
        violation.line === 0
          ? `${violation.path} (file name)`
          : `${violation.path}:${violation.line}:${violation.column}`;
      lines.push(`  ${where}  "${violation.text}"`);
      lines.push(`      ${describe(violation)}`);
    }
    lines.push(
      "",
      "  fix: move the code to the consumer, or turn it into an engine extension point " +
        "(config, hook, registry) the consumer fills in. excuse a hit only when it is " +
        "legitimate, in scripts/engine-boundary/excuses.json with a reason.",
    );
  }
  if (stale.length > 0) {
    if (lines.length > 0) lines.push("");
    lines.push(`engine boundary: ${stale.length} stale excuse(s)`, "");
    for (const { detail } of stale) {
      lines.push(
        `  ${detail}; delete it from scripts/engine-boundary/excuses.json`,
      );
    }
  }
  if (lines.length === 0) {
    lines.push(
      `engine boundary: clean (${fileCount} files, ${Math.round(elapsedMs)} ms)`,
    );
  }
  if (pending.length > 0) {
    lines.push(
      "",
      `engine boundary: ${pending.length} excuse(s) are debt with a named fix:`,
    );
    for (const excuse of pending) {
      lines.push(`  ${excuse.path}: until ${excuse.until}`);
    }
  }
  return lines.join("\n");
}

function parseArgs(argv) {
  const options = { vocabulary: null, isJson: false };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--vocabulary") {
      options.vocabulary = argv[index + 1];
      if (!options.vocabulary) throw new GateError("--vocabulary needs a file");
      index += 1;
    } else if (arg === "--json") {
      options.isJson = true;
    } else {
      throw new GateError(`unknown argument: ${arg}`);
    }
  }
  return options;
}

export function runGate({ root = ENGINE_ROOT, vocabularyPath = null } = {}) {
  const started = performance.now();
  const hashed = readJson(DENYLIST_PATH, "denylist");
  const vocabulary = vocabularyPath
    ? readJson(vocabularyPath, "vocabulary")
    : null;
  const denylist = buildDenylist(hashed, vocabulary);
  const excuses = readJson(EXCUSES_PATH, "excuses");
  const files = listEngineFiles(root);
  const violations = scanEngine({ root, denylist, files });
  const { remaining, stale } = applyExcuses({ violations, excuses, root });
  return {
    remaining,
    stale,
    pending: (excuses.excuses ?? []).filter((excuse) => excuse.until),
    fileCount: files.length,
    elapsedMs: performance.now() - started,
  };
}

function main() {
  let outcome;
  let options;
  try {
    options = parseArgs(process.argv.slice(2));
    outcome = runGate({ vocabularyPath: options.vocabulary });
  } catch (error) {
    if (!(error instanceof GateError)) throw error;
    process.stderr.write(`engine boundary: could not run: ${error.message}\n`);
    process.exit(2);
  }
  if (options.isJson) {
    process.stdout.write(`${JSON.stringify(outcome, null, 2)}\n`);
  } else {
    const report = formatReport(outcome);
    const isClean =
      outcome.remaining.length === 0 && outcome.stale.length === 0;
    (isClean ? process.stdout : process.stderr).write(`${report}\n`);
  }
  process.exit(
    outcome.remaining.length === 0 && outcome.stale.length === 0 ? 0 : 1,
  );
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main();
}
