use actix::{Actor, Addr};
use actix_web_actors::ws;

use crate::server::Server;

/// A session is a connection to the server.
pub struct Session {
    /// The unique identifier of the session, generated by the server.
    pub id: String,

    /// The address of the server.
    server_addr: Addr<Server>,
}

impl Actor for Session {
    type Context = ws::WebsocketContext<Self>;
}
