import {
  CanvasTexture,
  ClampToEdgeWrapping,
  Color,
  NearestFilter,
  SRGBColorSpace,
  Texture,
  Vector3,
  WebGLRenderer,
} from "three";

import { ThreeUtils } from "../../utils";

import { UV } from "./uv";

type AtlasAnimationPatch = {
  scratch: HTMLCanvasElement;
  x: number;
  y: number;
  size: number;
  dstPosition: Vector3;
};

/**
 * A texture atlas is a collection of textures that are packed into a single texture.
 * This is useful for reducing the number of draw calls required to render a scene, since
 * all block textures can be rendered with a single draw call.
 *
 * By default, the texture atlas creates an additional border around each texture to prevent
 * texture bleeding.
 *
 * ![Texture bleeding](/img/docs/texture-bleeding.png)
 *
 * @noInheritDoc
 */
export class AtlasTexture extends CanvasTexture {
  private static sharedUnknownTexture: AtlasTexture | null = null;

  /**
   * The number of textures per side of the texture atlas
   */
  public countPerSide: number;

  /**
   * Since the texture atlas is a square, the dimension is the length of one side.
   */
  public dimension: number;

  /**
   * The canvas that is used to generate the texture this.
   */
  public canvas: HTMLCanvasElement;

  /**
   * The margin between each block texture in the this.
   */
  public atlasMargin = 0;

  /**
   * The offset of each block's texture to the end of its border.
   */
  public atlasOffset = 0;

  /**
   * The ratio of the texture on the atlas to the original texture.
   */
  public atlasRatio = 0;

  /**
   * The list of block animations that are being used by this texture atlas.
   */
  public animations: { animation: FaceAnimation; timer: any }[] = [];

  private pendingAnimationPatches = new Map<
    FaceAnimation,
    AtlasAnimationPatch
  >();

  /**
   * Create a new texture this.
   *
   * @param textureMap A map that points a side name to a texture or color.
   * @param ranges The ranges on the texture atlas generated by the server.
   * @param options The options used to create the texture this.
   * @returns The texture atlas generated.
   */
  constructor(
    countPerSide: number,
    dimension: number,
    canvas = document.createElement("canvas"),
  ) {
    super(canvas);

    this.canvas = canvas;

    this.countPerSide = countPerSide;
    this.dimension = dimension;

    if (countPerSide === 1) {
      this.atlasOffset = 0;
      this.atlasRatio = 1;
      this.atlasMargin = 0;
    } else {
      this.atlasOffset = 1 / (countPerSide * 4);

      this.atlasMargin = 1;
      this.atlasRatio =
        (this.atlasMargin / this.atlasOffset / countPerSide -
          2 * this.atlasMargin) /
        dimension;

      while (this.atlasRatio !== Math.floor(this.atlasRatio)) {
        this.atlasRatio *= 2;
        this.atlasMargin *= 2;
      }
    }

    const canvasWidth =
      (dimension * this.atlasRatio + this.atlasMargin * 2) * countPerSide;
    const canvasHeight =
      (dimension * this.atlasRatio + this.atlasMargin * 2) * countPerSide;
    this.canvas.width = canvasWidth;
    this.canvas.height = canvasHeight;

    const context = this.canvas.getContext("2d");
    context.imageSmoothingEnabled = false;

    this.makeCanvasPowerOfTwo(this.canvas);
    this.wrapS = ClampToEdgeWrapping;
    this.wrapT = ClampToEdgeWrapping;
    this.minFilter = NearestFilter;
    this.magFilter = NearestFilter;
    this.generateMipmaps = false;
    this.needsUpdate = true;
    this.colorSpace = SRGBColorSpace;

    const unknown = AtlasTexture.makeUnknownImage(canvasWidth / countPerSide);

    for (let x = 0; x < countPerSide; x++) {
      for (let y = 0; y < countPerSide; y++) {
        context.drawImage(
          unknown,
          (x / countPerSide) * canvasWidth,
          (y / countPerSide) * canvasHeight,
          canvasWidth / countPerSide,
          canvasHeight / countPerSide,
        );
      }
    }
  }

  /**
   * Paints the entire canvas with a specified color using Three.js Color.
   *
   * @param color A Three.js Color instance to use for painting.
   */
  paintColor(color: Color) {
    this.drawImageToRange(
      {
        startU: 0,
        endU: 1,
        startV: 0,
        endV: 1,
      },
      color,
    );
  }

  /**
   * Draw a texture to a range on the texture atlas.
   *
   * @param range The range on the texture atlas to draw the texture to.
   * @param image The texture to draw to the range.
   */
  drawImageToRange(
    range: UV,
    image:
      | typeof Image
      | HTMLImageElement
      | HTMLCanvasElement
      | Color
      | Texture,
    clearRect = true,
    opacity = 1.0,
  ) {
    const { startU, endV } = range;

    const image2 = ThreeUtils.isTexture(image)
      ? (image.image as CanvasImageSource)
      : (image as HTMLImageElement);

    if (!image2) {
      return;
    }

    const context = this.canvas.getContext("2d");

    context.save();

    const canvasWidth = this.canvas.width;
    const canvasHeight = this.canvas.height;

    context.globalAlpha = opacity;

    if (opacity !== 1) context.globalCompositeOperation = "lighter";

    if (clearRect) {
      context.clearRect(
        (startU - this.atlasOffset) * canvasWidth,
        (1 - endV - this.atlasOffset) * canvasHeight,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
      );
    }

    if ((image as any as Color).isColor) {
      const originalColor = image as any as Color;
      // Use getHexString() directly - it returns the sRGB hex that was originally passed in
      // Do NOT use convertLinearToSRGB() as that would double-convert and wash out colors
      // When Color is created from hex string like "#9be9a8", getHexString() returns "9be9a8"
      context.fillStyle = `#${originalColor.getHexString()}`;
      context.fillRect(
        (startU - this.atlasOffset) * canvasWidth,
        (1 - endV - this.atlasOffset) * canvasHeight,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
      );

      return;
    }

    // Draw a background first.

    if (clearRect) {
      context.drawImage(
        image2,
        (startU - this.atlasOffset) * canvasWidth,
        (1 - endV - this.atlasOffset) * canvasHeight,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
        this.dimension * this.atlasRatio + 2 * this.atlasMargin,
      );

      // Carve out the middle.
      context.clearRect(
        (startU - this.atlasOffset) * canvasWidth + this.atlasMargin,
        (1 - endV - this.atlasOffset) * canvasHeight + this.atlasMargin,
        this.dimension * this.atlasRatio,
        this.dimension * this.atlasRatio,
      );
    }

    // Draw the actual texture.
    context.drawImage(
      image2,
      (startU - this.atlasOffset) * canvasWidth + this.atlasMargin,
      (1 - endV - this.atlasOffset) * canvasHeight + this.atlasMargin,
      this.dimension * this.atlasRatio,
      this.dimension * this.atlasRatio,
    );

    context.restore();

    this.needsUpdate = true;
  }

  registerAnimation(
    range: UV,
    keyframes: [number, Color | HTMLImageElement][],
    fadeFrames = 0,
  ) {
    const animation = new FaceAnimation(range, keyframes, fadeFrames);

    const entry = { animation, timer: null };

    // Animation ticks never set `needsUpdate` on this texture: doing so
    // re-uploads the entire atlas canvas to the GPU every tick, which for a
    // fading animation means a multi-megabyte texSubImage2D stall on nearly
    // every frame. Frames are composited on a per-animation scratch canvas
    // instead, mirrored onto the atlas canvas (so full uploads stay
    // coherent), and queued as a small sub-rectangle GPU patch that the
    // world flushes before rendering.
    const patch = this.makeAnimationPatch(animation);

    const start = (index = 0) => {
      const keyframe = animation.keyframes[index];

      this.drawAnimationKeyframe(
        patch,
        keyframe[1],
        this.countPerSide !== 1,
        1,
      );
      this.commitAnimationPatch(animation, patch);

      entry.timer = setTimeout(() => {
        clearTimeout(entry.timer);

        const nextIndex = (index + 1) % animation.keyframes.length;

        if (fadeFrames > 0) {
          const nextKeyframe = animation.keyframes[nextIndex];

          const fade = (fraction = 0) => {
            if (fraction > fadeFrames) {
              start(nextIndex);
              return;
            }

            requestAnimationFrame(() => fade(fraction + 1));

            this.drawAnimationKeyframe(
              patch,
              nextKeyframe[1],
              true,
              fraction / fadeFrames,
            );
            this.drawAnimationKeyframe(
              patch,
              keyframe[1],
              false,
              1 - fraction / fadeFrames,
            );
            this.commitAnimationPatch(animation, patch);
          };

          fade();
        } else {
          start(nextIndex);
        }
      }, keyframe[0]);
    };

    this.animations.push(entry);

    start();
  }

  private makeAnimationPatch(animation: FaceAnimation): AtlasAnimationPatch {
    const { startU, endV } = animation.range;
    const canvasWidth = this.canvas.width;
    const canvasHeight = this.canvas.height;
    const size = Math.round(
      this.dimension * this.atlasRatio + 2 * this.atlasMargin,
    );
    const x = Math.round((startU - this.atlasOffset) * canvasWidth);
    const y = Math.round((1 - endV - this.atlasOffset) * canvasHeight);

    const scratch = document.createElement("canvas");
    scratch.width = size;
    scratch.height = size;
    scratch.getContext("2d").imageSmoothingEnabled = false;

    return {
      scratch,
      x,
      y,
      size,
      // texSubImage2D destinations are addressed from the texture's bottom
      // row; the atlas uploads with flipY, so the canvas-space rect flips.
      dstPosition: new Vector3(x, canvasHeight - y - size, 0),
    };
  }

  private drawAnimationKeyframe(
    patch: AtlasAnimationPatch,
    image: Color | HTMLImageElement,
    clearRect: boolean,
    opacity: number,
  ) {
    const context = patch.scratch.getContext("2d");
    const size = patch.size;
    const inner = this.dimension * this.atlasRatio;

    context.save();
    context.globalAlpha = opacity;
    if (opacity !== 1) context.globalCompositeOperation = "lighter";

    if (clearRect) {
      context.clearRect(0, 0, size, size);
    }

    if ((image as Color).isColor) {
      context.fillStyle = `#${(image as Color).getHexString()}`;
      context.fillRect(0, 0, size, size);
      context.restore();
      return;
    }

    const source = image as HTMLImageElement;

    // Same margin-bleed layout as drawImageToRange: a padded backdrop, a
    // carved center, then the actual texture in the center.
    if (clearRect) {
      context.drawImage(source, 0, 0, size, size);
      context.clearRect(this.atlasMargin, this.atlasMargin, inner, inner);
    }

    context.drawImage(source, this.atlasMargin, this.atlasMargin, inner, inner);

    context.restore();
  }

  private commitAnimationPatch(
    animation: FaceAnimation,
    patch: AtlasAnimationPatch,
  ) {
    // Keep the CPU-side atlas canvas coherent so any later full upload
    // (context loss, needsUpdate from static texture edits) stays correct.
    const context = this.canvas.getContext("2d");
    context.clearRect(patch.x, patch.y, patch.size, patch.size);
    context.drawImage(patch.scratch, patch.x, patch.y);

    this.pendingAnimationPatches.set(animation, patch);
  }

  flushAnimationPatches(renderer: WebGLRenderer) {
    // Called by the world right before rendering: queued animation frames
    // upload as sub-rectangle patches of the GPU texture. No-op when no
    // animation ticked since the last flush.
    if (this.pendingAnimationPatches.size === 0) return;

    const textureProperties = renderer.properties.get(this) as {
      __webglTexture?: WebGLTexture;
    };
    if (!textureProperties.__webglTexture) {
      // Not GPU-resident yet: the atlas canvas already mirrors every patch,
      // so a full upload on the next bind covers them.
      this.pendingAnimationPatches.clear();
      this.needsUpdate = true;
      return;
    }

    // Raw texSubImage2D instead of renderer.copyTextureToTexture: the three
    // helper brackets every copy with five synchronous gl.getParameter
    // round-trips to the GPU process (to save/restore unpack state), which
    // stall the main thread for longer than the upload itself. Unpack state
    // is instead set to the defaults three's own uploads assume.
    const gl = renderer.getContext();
    renderer.state.bindTexture(gl.TEXTURE_2D, textureProperties.__webglTexture);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, this.flipY);
    gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, this.premultiplyAlpha);
    gl.pixelStorei(gl.UNPACK_ALIGNMENT, this.unpackAlignment);
    gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL, gl.NONE);

    this.pendingAnimationPatches.forEach((patch) => {
      gl.texSubImage2D(
        gl.TEXTURE_2D,
        0,
        patch.dstPosition.x,
        patch.dstPosition.y,
        gl.RGBA,
        gl.UNSIGNED_BYTE,
        patch.scratch,
      );
    });
    this.pendingAnimationPatches.clear();

    renderer.state.unbindTexture();
  }

  private makeCanvasPowerOfTwo(canvas?: HTMLCanvasElement | undefined) {
    let setCanvas = false;
    if (!canvas) {
      canvas = this.canvas;
      setCanvas = true;
    }
    const oldWidth = canvas.width;
    const oldHeight = canvas.height;
    const newWidth = Math.pow(2, Math.round(Math.log(oldWidth) / Math.log(2)));
    const newHeight = Math.pow(
      2,
      Math.round(Math.log(oldHeight) / Math.log(2)),
    );
    const newCanvas = document.createElement("canvas");
    newCanvas.width = newWidth;
    newCanvas.height = newHeight;
    newCanvas.getContext("2d")?.drawImage(canvas, 0, 0, newWidth, newHeight);
    if (setCanvas) {
      this.canvas = newCanvas;
    }
  }

  static makeUnknownImage(
    dimension: number,
    color1 = "#FF00FF",
    color2 = "#000000",
  ) {
    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");

    context.imageSmoothingEnabled = false;
    context.canvas.width = dimension;
    context.canvas.height = dimension;

    const halfDim = dimension / 2;

    context.fillStyle = color1;
    context.fillRect(0, 0, halfDim, halfDim);
    context.fillRect(halfDim, halfDim, halfDim, halfDim);

    context.fillStyle = color2;
    context.fillRect(halfDim, 0, halfDim, halfDim);
    context.fillRect(0, halfDim, halfDim, halfDim);

    return canvas;
  }

  static makeUnknownTexture(dimension: number) {
    if (AtlasTexture.sharedUnknownTexture) {
      return AtlasTexture.sharedUnknownTexture;
    }

    const newAtlas = new AtlasTexture(1, dimension);
    const image = AtlasTexture.makeUnknownImage(dimension);

    newAtlas.drawImageToRange(
      {
        startU: 0,
        endU: 0,
        startV: 0,
        endV: 0,
      },
      image,
    );

    newAtlas.minFilter = NearestFilter;
    newAtlas.magFilter = NearestFilter;
    newAtlas.generateMipmaps = false;
    newAtlas.needsUpdate = true;
    newAtlas.colorSpace = SRGBColorSpace;

    AtlasTexture.sharedUnknownTexture = newAtlas;
    return newAtlas;
  }
}

/**
 * The animation data that is used internally in an atlas texture. This holds the data and will be used to draw on the texture atlas.
 */
export class FaceAnimation {
  /**
   * The range of the texture atlas that this animation uses.
   */
  public range: UV;

  /**
   * The keyframes of the animation. This will be queried and drawn to the
   * texture atlas.
   */
  public keyframes: [number, HTMLImageElement | Color][];

  /**
   * The fading duration between each keyframe in milliseconds.
   */
  public fadeFrames: number;

  /**
   * Create a new face animation. This holds the data and will be used to draw on the texture atlas.
   *
   * @param range The range of the texture atlas that this animation uses.
   * @param keyframes The keyframes of the animation. This will be queried and drawn to the texture atlas.
   * @param fadeFrames The fading duration between each keyframe in milliseconds.
   */
  constructor(
    range: UV,
    keyframes: [number, HTMLImageElement | Color][],
    fadeFrames = 0,
  ) {
    if (!range) {
      throw new Error("Texture range is required for FaceAnimation.");
    }

    if (keyframes.length <= 1) {
      throw new Error("FaceAnimation must have at least two keyframe.");
    }

    this.range = range;
    this.keyframes = keyframes as any;
    this.fadeFrames = fadeFrames;
  }
}
